testfile = open("testfile.txt","w")
testfile.write("My name is Vishnu")
testfile = open("testfile.txt","r")
content = testfile.read()
print(content)
testfile.close()
newfile = open("testfile.txt","a")
newfile.write("\n"+"Learning Python")
newfile = open("testfile.txt","r")
updatedcontent = newfile.read()
print(updatedcontent)
newfile.close()
